# Generated by Django 2.2.7 on 2020-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('empName', models.CharField(max_length=50)),
                ('empDesig', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
