# Generated by Django 2.2.7 on 2020-04-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_emp_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='first_name',
            new_name='frist_name',
        ),
    ]
