# Generated by Django 2.2.7 on 2020-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.FileField(upload_to='profilepics/'),
        ),
    ]
