# Generated by Django 2.2.7 on 2020-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mailId', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
